export enum VMSocketTriggerTypes {
  JOIN_ROOM = "join-room",
  ICE_CANDIDATE = "ice-candidate",
  RECEIVE_ICE_CANDIDATE = "receive-ice-candidate",
  OFFER = "offer",
  ANSWER = "answer",
  USER_JOINED = "user-joined",
  RECEIVE_OFFER = "receive-offer",
  RECEIVE_ANSWER = "receive-answer",
  EXISTING_USERS = "existing-users",
  USER_LEAVED = 'user-leaved',
  LEAVE_ROOM = "leave-room",
  INVITE_WAITING = "invite-waiting",
}

export enum SocketTriggerTypes {
  REGISTER_USER = "REGISTER_USER",
  RECEIVED_NOTIFICATION = "RECEIVED_NOTIFICATION",
  USER_SLOT_BOOKED = "USER_SLOT_BOOKED",
  USER_SLOT_UNBOOKED = "USER_SLOT_UNBOOKED",
  INCREASE_BOOKED_USER = "INCREASE_BOOKED_USERS",
  DECREASE_BOOKED_USER = "DECREASE_BOOKED_USER",
  MEETING_TIME_STARTED = "MEETING_TIME_STARTED",
  MEETING_STARTED = "MEETING_STARTED",
  HOST_JOINED = "HOST_JOINED",
  NEW_PARTICIPANT_JOINED = "NEW_PARTICIPANT_JOINED",
  NEW_METING_CHAT_MESSAGE = "NEW_METING_CHAT_MESSAGE",
  DELETE_METING_CHAT_MESSAGE = "DELETE_METING_CHAT_MESSAGE",
  CHANGE_MEETING_SETTING = "CHANGE_MEETING_SETTING",
  LEAVE_ROOM = "LEAVE_ROOM",
  USER_LEAVED = "USER_LEAVED",
  MEETING_ENDED = "MEETING_ENDED",
  RUNNING_VIDEO_MEETING_CANCELLED = "RUNNING_VIDEO_MEETING_CANCELLED",
  SEND_NEW_CHAT_MESSAGE = "SEND_NEW_CHAT_MESSAGE",
  DELETE_CHAT_MESSAGE = "DELETE_CHAT_MESSAGE",
  INCREASE_UNSEEN_MESSAGE_COUNT = "INCREASE_UNSEEN_MESSAGE_COUNT",
  UPDATE_MESSAGE_SEEN = "UPDATE_MESSAGE_SEEN"
}

export enum IVideoCallStatus {
  WAITING = 'waiting',
  ACTIVE = 'active',
  ENDED = 'ended',
  LEAVED = 'leaved',
}